### ISSUE TITLE
Ability to pass array of controllers to decorators.add.call()

### ISSUE THREAD

**Issue by brownish** [loggur/baucis-decorator-deep-select#1]
I love love it if I could pass an array of controllers to the decorators.add.call function instead of doing it one-by-one or iterating over the array. Is this possible?

Thanks!

**Comment by timbur** [comment]
Just to clarify before I make any changes to [baucis-decorators](`https://github.com/loggur/baucis-decorators`), do you mean something like this?

```js
var controllers = [ResourceController, LogController, UserController];
var decorators = ['baucis-decorator-deep-select'];

decorators.add.call(controllers, decorators);
```

**Comment by brownish** [comment]
Exactly. I tried that but I don't think it worked. I was also having another issue selecting (select=-geometry) AND populating (i.e. select=sites.descriptions), which together would be select=-geometry sites.descriptions. Apparently you can't deselect and select in the same query?

**Comment by timbur** [comment]
> Apparently you can't deselect and select in the same query?

Yeah I believe either mongo or mongoose throws an error when you do that, which makes sense because when you select properties, you're telling mongo you only want those properties, so there's no point in deselecting any others.  And the only time it might make sense to deselect properties is when you know you want all properties except for the ones specified, which is something I've actually never found a use for, but I'm sure it could be useful in some cases.  I don't think I designed this decorator to support that particular functionality but it would be trivial to add it.

I'll implement the ability to use an array of controllers real quick.

**Comment by timbur** [comment]
You should be able to use an array of controllers now.  See the change [here](https://github.com/loggur/baucis-decorators/commit/5a250d0ab20891eade6efa393e4c721690f9f3fc).  You should be able to use `npm update baucis-decorators --save`.  Let me know if for some reason it doesn't work for you.

**Comment by timbur** [comment]
Also, I might move [https://github.com/loggur/baucis-decorator-deep-select/blob/master/temp-mongoose-patch.js](temp-mongoose-patch.js) to its own repo so that regular mongoose users have it as an alternative to `mongoose-deep-select` until mongoose 4.2 is out.  See my [pull request](https://github.com/Automattic/mongoose/pull/2916) for details on how the patch (4.2 deep select) will work.

**Comment by timbur** [comment]
Whoops.  Fixed a [silly mistake](https://github.com/loggur/baucis-decorators/commit/49b9efcde6510a6c9d54f7481dc807ca9eab6fad).  Make sure to use `baucis-decorators` v1.0.4.

**Comment by brownish** [comment]
Thanks for the quick response! Regarding deselecting and selecting at the same time, I have datasets containing geometry objects with pretty large arrays of coordinates that I would like to deselect (in a tabular view rather than a map view) so the query is faster and response is smaller. However, I would like to deep populate children as well. Using the select as populate method, can this be done? If not, do you have any ideas on how to address this issue?

**Comment by timbur** [comment]
Are you using [`baucis`](https://github.com/wprl/baucis)?  This decorator is designed to work with `baucis` controllers.

Either way, you should be able to pull [`temp-mongoose-patch.js`](https://github.com/loggur/baucis-decorator-deep-select/blob/master/temp-mongoose-patch.js) from this repo (until `mongoose@^4.2.0`) and use it to perform any combination of `select` and `populate`.  It will allow you to do stuff like this:
```js
Comment.populate({
  path: 'createdBy',
  model: 'User',
  select: '-level',             // select all but `level` property
  populate: [{
    path: 'followers',          // populate user's followers
    select: 'name followers',   // select only their name and followers
    options: { limit: 5 },
    populate: {                 // can also use a single object instead of array of objects
      path: 'followers',        // populate the followers' followers
      select: 'name',           // etc.
      options: { limit: 2 }
    }
  }]
});
```

I actually haven't yet verified that the patch itself works lol, as I've been using a modified `mongoose` instead, but it should work in theory.  Let me know if it doesn't.  :)

**Comment by brownish** [comment]
I am using baucis. What you're showing there is pretty much what I'd like to do. How would I pass that a query like that to the API using a get request?

Something like /api/v1/asdf?populate={"path": "createdBy", "model": "User", "select": "-level", ...}  ?

Do I need to wire anything additional up while defining controllers and/or models?

**Comment by timbur** [comment]
> Something like /api/v1/asdf?populate={"path": "createdBy", "model": "User", "select": "-level", ...} ?

That might work.  Try it out and let me know.  In the mean time, I'll explain a bit.

All this decorator does is convert something like `/api/comment/123?select=createdBy.followers.name createdBy.followers.followers.name` to the above `Comment.populate` argument (nested select+populate object).  The temporary patch is for `mongoose` itself, as it's easier and more efficient to handle the deep population within `mongoose`'s internals, and it's kinda where all the real "magic" happens.

So you should in theory be able to use your `asdf?populate={...}` query and it will just work, with or without this decorator, as long as you're either using the temporary patch or a patched version of `mongoose`.  Although, you'll probably need to set the [`req.baucis.allowPopulateSelect` flag](https://github.com/wprl/baucis/blob/master/Controller/query/options.js#L86-L116) to `true`.

I should probably add some tests or something to verify that the temporary patch works correctly in this context.  Although it may not be worth the effort since the real patch has been [bumped up to `mongoose@4.1`](https://github.com/Automattic/mongoose/pull/3103#issuecomment-120032165).

**Comment by brownish** [comment]
Ahh, gotcha. That makes much more sense. I'll give it a shot and let you know how it goes.

**Comment by timbur** [comment]
Just tried out the temp patch lol.  Didn't work, and it looks like it'll be a bit of a pain to fix it, so use my fork of `mongoose` instead.  I believe this should work:
`npm install timbur/mongoose --save`

**Comment by brownish** [comment]
I've got some basic questions that are messing me up (probably since I'm a total javascript newb).

To keep it simple, I'm trying this out with 2 models:

States:
```
var mongoose = require('mongoose'),
    Schema = mongoose.Schema,
    relationship = require("mongoose-relationship");

var StateSchema = new Schema({
  name: {type: String, required: true},
  abbreviation: String,
  smithsonian_code: Number,
  fips_code: Number,
  counties: [{ type: Schema.Types.ObjectId, ref: 'County' }],
  geometry: {
    type: {type: String},
    coordinates: []
  }
});
StateSchema.index({geometry: '2dsphere'});
module.exports = mongoose.model('State', StateSchema);
```

Counties:
```
var mongoose = require('mongoose'),
    Schema = mongoose.Schema,
    relationship = require("mongoose-relationship");


var CountySchema = new Schema({
    name: String,
    smithsonian_code: String,
    fips_code: Number,
    state: { type: Schema.Types.ObjectId, ref: 'State', childPath: "counties"},
    sites: [{ type: Schema.Types.ObjectId, ref: 'Site' }],
    geometry: {
        type: {type: String},
        coordinates: []
    }
});
CountySchema.index({geometry: '2dsphere'});
CountySchema.plugin(relationship, {relationshipPathName: 'state'});
module.exports = mongoose.model('County', CountySchema);
```

And a baucis API written pretty much like so:
```
var express = require('express');
var baucis = require('baucis');
var vivify = require('baucis-vivify');
var decorators = require('baucis-decorators');

module.exports = function(app) {
    var governmentAPI = baucis();
    var states = baucis.rest('State');
    var counties = baucis.rest('County');
    var state_counties = states.vivify('counties');
    decorators.add.call([states, counties], [
        'baucis-decorator-deep-select'
    ]);
    app.use('/api/v1/government', baucis());
}
```

With those models and the baucis API code, will the temp-mongoose-patch code be injected and allow for subpopulation? Where do I set the req.baucis.allowPopulateSelect flag to true? With the above code, I can't subpopulate and deselect.

**Comment by timbur** [comment]
I removed the temp patch from this decorator.  You should be able to use `npm update baucis-decorator-deep-select --save` and then make sure you're using `timbur/mongoose`.  If you run into any problems (peer dependencies, etc.), try removing `node_modules` then installing `timbur/mongoose` first and then `npm install` to reinstall the others.

> Where do I set the req.baucis.allowPopulateSelect flag to true?

`baucis-decorator-deep-select` will set `req.baucis.allowPopulateSelect` to `true` if it detects a nested `select` query parameter.  But if you're going to pass a JSON object to the `populate` query parameter, you'll need to set it to true yourself.  You can do it a few different ways, but this should work:

```js
var express = require('express');
var baucis = require('baucis');
var vivify = require('baucis-vivify');
var decorators = require('baucis-decorators');

module.exports = function(app) {
    var governmentAPI = baucis();
    var states = baucis.rest('State');
    var counties = baucis.rest('County');
    var controllers = [states, counties];
    var state_counties = states.vivify('counties');

    decorators.add.call(controllers, [
        'baucis-decorator-deep-select'
    ]);

    controllers.forEach(function (controller) {
        controller.use(function (req, res, next) {
            req.baucis.allowPopulateSelect = true;
            next();
        });
    });

    app.use('/api/v1/government', baucis());
}
```

**Comment by brownish** [comment]
GET `api/v1/government/counties?populate={"path": "state", "model": "State", "select": "-geometry"}` returned the correct response!
GET `api/v1/government/counties?select=name smithsonian_code fips_code state.name state.smithsonian_code state.fips_code state.abbreviation` also returned the correct response!

So it looks like I can pass use JSON object or dotted notation to return the correct response. Awesome!

**Comment by timbur** [comment]
Nice!  Glad to see it works for you.  :)

**Comment by brownish** [comment]
Thanks for all your assistance!
